Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.hostname = "escola-masters"

  config.vm.provider "virtualbox" do |v|
    v.name = "escola-masters"
    v.memory = 2048
    v.cpus = 2
    v.customize ['modifyvm', :id, '--clipboard', 'bidirectional']
  end

  config.vm.synced_folder "./codi", "/var/www/html"
  config.vm.synced_folder "./scripts", "/home/vagrant/scripts"

  config.vm.network "public_network"

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update -y

    # Paquets bàsics
    sudo apt-get install -y net-tools whois nano aptitude unzip curl

    # Docker 
    sudo apt-get install -y apt-transport-https ca-certificates gnupg2 software-properties-common
    curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
    sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
    sudo apt-get update -y
    sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose

    # Apache, PHP i MariaDB
    sudo apt-get install -y apache2 libapache2-mod-php php8.2 mariadb-server mariadb-client php8.2-mysql

    # Extensions de PHP per Laravel
    sudo apt-get install -y php-bcmath php-json php-mbstring php-tokenizer php-xml php-zip php-curl

    # Composer
    sudo apt-get install -y composer

    # Permisos
    sudo gpasswd -a vagrant docker
    sudo gpasswd -a vagrant www-data
    sudo chmod -R 770 /var/www/html

    exit
  SHELL
end